// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBmM0EIQlsj_aziedvx77oI6x8i0nisTMQ',
    appId: '1:316429966390:web:011b8fefc52049dfbb8c97',
    messagingSenderId: '316429966390',
    projectId: 'hackathon2023-e4fc1',
    authDomain: 'hackathon2023-e4fc1.firebaseapp.com',
    storageBucket: 'hackathon2023-e4fc1.appspot.com',
    measurementId: 'G-55DHKN3Y4V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBdVF_XrN-kh_Zmu12JDRxyvc_eUl3Cnmg',
    appId: '1:316429966390:android:aa3ff812010c2940bb8c97',
    messagingSenderId: '316429966390',
    projectId: 'hackathon2023-e4fc1',
    storageBucket: 'hackathon2023-e4fc1.appspot.com',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD3aebRDzm-1E-K9vDixXxVDSN6R0tQSwY',
    appId: '1:316429966390:ios:2fffd6aab251f005bb8c97',
    messagingSenderId: '316429966390',
    projectId: 'hackathon2023-e4fc1',
    storageBucket: 'hackathon2023-e4fc1.appspot.com',
    iosBundleId: 'com.example.front.RunnerTests',
  );
}
